### ISSUE TITLE
Failed to build on Ubuntu 15.04: incompatible return type

### ISSUE THREAD

**Issue by rymate1234** [Valama/valama#171]
Running stock ubuntu 15.04 (originally said 15.10 whoops) with the vala ppa, however I'm getting an error when compiling
````
/home/ryan/valama/src/completion_provider.vala:180.5-180.38: error: overriding method `GuanakoCompletion.get_icon' is incompatible with base method `Gtk.SourceCompletionProvider.get_icon': incompatible return type.
    public unowned Gdk.Pixbuf get_icon() {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ryan/valama/src/completion_provider.vala:224.5-224.45: error: overriding method `GuanakoCompletion.get_info_widget' is incompatible with base method `Gtk.SourceCompletionProvider.get_info_widget': incompatible return type.
    public unowned Gtk.Widget get_info_widget (Gtk.SourceCompletionProposal proposal) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 0 warning(s)
````

Vala version is 0.26.2

**Comment by inizan-yannick** [comment]
15.10 ? O_o
GtkSourceView team have updated his vapi - these elements are nullable. please try my last commit : https://github.com/inizan-yannick/valama

**Comment by rymate1234** [comment]
That worked! Thanks :)

**Comment by inizan-yannick** [comment]
you can close issue now
