### ISSUE TITLE
Can't bulid with Gdl 3.6.0

### ISSUE THREAD

**Issue by eric-yorba** [Valama/valama#47]
Trying to compile with Gdl 3.6.0, I get the following errors:

```
/home/eric/Development/valama/src/ui_main.vala:601.32-601.54: error: The name `flags' does not exist in the context of `Gdl.DockItem?'
        btn_element.active = ((element.dock_item.flags & DockObjectFlags.ATTACHED) != 0);
                               ^^^^^^^^^^^^^^^^^^^^^^^
/home/eric/Development/valama/src/ui_main.vala:560.38-560.60: error: The name `flags' does not exist in the context of `Gdl.DockItem?'
        item_view_element.active = ((element.dock_item.flags & DockObjectFlags.ATTACHED) != 0);
                                     ^^^^^^^^^^^^^^^^^^^^^^^
/home/eric/Development/valama/src/ui/ui_elements.vala:137.38-137.52: error: The name `flags' does not exist in the context of `Gdl.DockItem?'
                            show = ((dock_item.flags & Gdl.DockObjectFlags.ATTACHED) != 0);
                                     ^^^^^^^^^^^^^^^
Compilation failed: 3 error(s), 0 warning(s)
```

From the source, it looks like version 3.6.2 is hard coded: 
 #if GDL_3_6_2

Looks to me like the API changed was in GDL 3.6.0 -- if I comment out the #if and the entire else block, the 3.6.2 version compiles just fine.
